[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x3c3836"  # Darker brown
blue = "0x458588"   # Blue-green
cyan = "0x689d6a"   # Green
green = "0x98971a"  # Olive green
magenta = "0xb16286"  # Pinkish-red
red = "0xcc241d"    # Red
yellow = "0xd79921" # Dark Yellow

[colors.primary]
background = "0x282828"  # Dark brown
foreground = "0xfbf1c7"  # Light cream

[font]
size = 11

[font.bold]
family = "Cascadia Mono"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Cascadia Mono"

[font.normal]
family = "Cascadia Mono"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.8

[window.padding]
x = 5
y = 5
